server:
  port: 5005
spring:


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3307/yt_job_portal_application
    #url: jdbc:postgresql://localhost:5432/yt_job_portal_application
    username: root
    password: system
    driver-class-name: com.mysql.jdbc.Driver

    #driver-class-name: org.postgresql.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
